# Generated by Django 4.2.7 on 2023-11-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="berat_badan",
        ),
        migrations.RemoveField(
            model_name="user",
            name="jenis_kelamin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kewarganegaraan",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nama_lengkap",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tinggi_badan",
        ),
    ]
