# Generated by Django 4.2.7 on 2023-12-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingans',
            name='digital_signature',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
