# Generated by Django 4.2.7 on 2023-11-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postingans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postingans",
            name="file_format",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
