# Generated by Django 4.2.7 on 2023-11-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdata",
            name="encrypted_berat_badan",
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="encrypted_nama_panjang",
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="encrypted_tinggi_badan",
        ),
        migrations.AddField(
            model_name="userdata",
            name="private_key",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdata",
            name="public_key",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
